provider:
  name: UKB
  author: Universitätsklinikum Bonn, Stabsstelle Medizinisch-Wissenschaftliche Technologieentwicklung und -koordination, Datenintegrationszentrum, Venusberg-Campus 1, 53127 Bonn

global:
  ## Adding data items that contain the case numbers and show the composition of the aggregated numbers
  debug: false
  ## The type of the server that is used for data retrieval whether its FHIR (any fhir server) or ACUWAVE
  server-type: FHIR
  ## Maximum 'count' size per fhir search request (e.g. if querying encounter resources by patient IDs). This value should never be reached (default: 1000000).
  # max-count-size: 1000000
  ## Comma-separated list of codes used for Corona patient identification (icd = Condition resources; loinc = Observation resources).
  inputcodes:
    ## ICD codes SARS-CoV-2
    condition: U07.1,U07.2
    ## LOINC-Codes SARS-CoV-2 PCR tests [96895-8 for variant results]
    observation:
      pcr: 94640-0,94306-8,96763-8,94500-6
      variants: 96895-8,96741-4
    ## Ventilation snomed ct codes [Procedure.code.coding.code]
    procedure:
      ecmo: 265764009,341939001,127788007,233572003,302497006,233586004,233581009,182750009,714749008,233573008,233578004,233575001,233588003,233583007,233594006,72541002,233574002,786452006,786451004,786453001,233579007,233580005,708932005,427053002,57274006,233577009,233576000,11932001,698074000,233589006,233590002,708933000,233587008,708930002,233584001,233585000,715743002,233582002,708934006,14130001000004100,182749009,438839005,83794005,77257005,448955002,20720000,233564000,233565004,225067007,19647005
      ventilation: 26763009,243147009,26763009,243141005,11140008,428311008,243160003,182687005,286812008,33050008,45851008,55089006,8948006,45851008,229306004,243180002,243161004,243164007,182687005,243151006,59427005,286812008,47545007,243142003,37113006,243157005,243170001,371908008,243163001,243162006,243167000,243166009,243169002,243168005,243150007,243156001,243148004,243149007,243154003,243155002,243153009,243152004,286813003,408852001,408853006,286813003,448442005,405609003,66852000,4764004,243143008,448134000,229308003,34281000175105,34291000175108,243144002,229312009,425447009,243140006,229313004,425696007,243184006,74596007,243181003,243183000,243182005,52729008,76777009,38282001,773454006,281508008,276737004,276732005,243159008,243158000,243172009,243171002,82433009,447837008,870392006,243146000,429253002,371907003,398077001,182714002,243136002,315041000,426990007,304577004,870533002,71786000
    prediction-models:
      ukb-renal-replacement-procedures:
        observations: 2160-0, 32693-4, 3091-6, 9187-6
    influenza:
      conditions: J10.0,J10.1,J10.8,J09
      observations: 34487-9,60416-5,49521-8,49531-7,61365-3,48509-4,29909-9,40982-1
  ## Option to active/deactivate certain workflows/outputs
  generate-covid-data: true
  generate-influenza-data: false
  generate-ukb-renal-replacement-model-data: false
fhir:
  server:
    ## The authentication method, one of NONE, SSL or BASIC (default)
    auth-method: BASIC
    ## the base url of the fhir server (needs to end with a "/")
    rest-url: http://127.0.0.1/fhir/
    ## BASIC
    rest-user: x
    rest-password: y
    ## SSL
    key-store: src/main/resources/certs/clinical_domain_keystore.jks
    key-store-password: Meine Vorfahren und Nachfahren
    trust-store: src/main/resources/certs/truststore.jks
    trust-store-password: Scheme Dream Martinique 739

  ## Adjustment of FHIR search requests on the FHIR server
  search:
    ## Batch size of the partial FHIR searches. If the length of the GET request URL is too long, this value must be reduced.
    batchsize: 500
    ## Maximum 'count' size per fhir search request (e.g. if querying encounter resources by patient IDs). This value should never be reached (default: 1000000).
    # max-count-size: 1000000
    ## Filter the patient (and thus also the encounter) retrieval to SARS-CoV-2-patients only
    # covid-filter-patient-retrieval: false
    ## Should the encounter fhir search query be filtered by admission date (all cases by SARS-CoV-2 start reference date) ? Must be disabled if outpatient cases do not have an end date.
    # covid-filter-encounter-by-date: false
    ## Does a Reference exist from Condition to Case or only the reverse way from Encounter to Condition? This results in differences in the FHIR search queries.
    # use-encounter-condition-reference: true 
    ## Filter the patient (and thus also the encounter) retrieval to influenza positive patients only which will reduce the data load
    # influenza-filter-patient-retrieval: false

## Switching off data items in the output on demand. For data items that are excluded, please comment out the corresponding line(s).
data-items:
  excludes:
    current.treatmentlevel: false
    current.maxtreatmentlevel: false
    current.age.maxtreatmentlevel.normal_ward: false
    current.age.maxtreatmentlevel.icu: false
    current.age.maxtreatmentlevel.icu_with_ventilation: false
    current.age.maxtreatmentlevel.icu_with_ecmo: false
    cumulative.results: false
    cumulative.gender: false
    cumulative.age: false
    cumulative.maxtreatmentlevel: false
    cumulative.zipcode: false
    cumulative.inpatient.gender: false
    cumulative.outpatient.gender: false
    cumulative.inpatient.age: false
    cumulative.outpatient.age: false
    cumulative.lengthofstay.icu: false
    cumulative.lengthofstay.icu.alive: false
    cumulative.lengthofstay.icu.dead: false
    cumulative.lengthofstay.hospital: false
    cumulative.lengthofstay.hospital.alive: false
    cumulative.lengthofstay.hospital.dead: false
    cumulative.varianttestresults: false
    cumulative.age.maxtreatmentlevel.outpatient: false
    cumulative.age.maxtreatmentlevel.normal_ward: false
    cumulative.age.maxtreatmentlevel.icu: false
    cumulative.age.maxtreatmentlevel.icu_with_ventilation: false
    cumulative.age.maxtreatmentlevel.icu_with_ecmo: false
    timeline.tests: false
    timeline.test.positive: false
    timeline.maxtreatmentlevel: false
    timeline.varianttestresults: false
    timeline.deaths: false
    ## Influenza related items
    infl.current.treatmentlevel: false
    infl.current.maxtreatmentlevel: false
    infl.current.age.maxtreatmentlevel.normal_ward: false
    infl.current.age.maxtreatmentlevel.icu: false
    infl.current.age.maxtreatmentlevel.icu_with_ventilation: false
    infl.current.age.maxtreatmentlevel.icu_with_ecmo: false
    infl.cumulative.results: false
    infl.cumulative.gender: false
    infl.cumulative.age: false
    infl.cumulative.maxtreatmentlevel: false
    infl.cumulative.zipcode: false
    infl.cumulative.inpatient.gender: false
    infl.cumulative.outpatient.gender: false
    infl.cumulative.inpatient.age: false
    infl.cumulative.outpatient.age: false
    infl.cumulative.lengthofstay.icu: false
    infl.cumulative.lengthofstay.icu.alive: false
    infl.cumulative.lengthofstay.icu.dead: false
    infl.cumulative.lengthofstay.hospital: false
    infl.cumulative.lengthofstay.hospital.alive: false
    infl.cumulative.lengthofstay.hospital.dead: false
    infl.cumulative.age.maxtreatmentlevel.outpatient: false
    infl.cumulative.age.maxtreatmentlevel.normal_ward: false
    infl.cumulative.age.maxtreatmentlevel.icu: false
    infl.cumulative.age.maxtreatmentlevel.icu_with_ventilation: false
    infl.cumulative.age.maxtreatmentlevel.icu_with_ecmo: false
    infl.timeline.tests: false
    infl.timeline.test.positive: false
    infl.timeline.maxtreatmentlevel: false
    infl.timeline.deaths: false
    ## internal items of the ukb
    current.treatmentlevel.crosstab: true
server:
  port: 9091

spring:
  security:
    user:
      name: user
      password: pwd

#reports:
## Should a file be generated with the case/encounter ids of active cases separated by treatment level?
# caseid-file-generation: true
# caseid-file-directory: X:\currentTreatmentlevelExport
# caseid-file-basename: CaseIdsByTreatmentlevel

#acuwave-server:
# rest-url: http://127.0.0.1/data/
## BASIC auth settings
# rest-user: x
# rest-password: y
## Adjustment of the search requests via acuwave module chain
## Orbis internal lab codes for positive SARS-Cov-2 PCR fundings
# covid-orbis-lab-pcr-codes: 19937,20057,20097,20117,20217,20238,20297,20298,20337,20517,20997,21857
# covid-orbis-lab-variant-codes: 21997,22017,22117
## Filter the patient (and thus also the encounter) retrieval to SARS-CoV-2-patients only
# filter-patient-retrieval: true
## Filter the procedure retrieval to inpatient SARS-CoV-2-cases only (with at least one icu transfer) to reduce the requests on an external server (experimental state)
# filter-procedure-retrieval: true
## Should procedures also be queried for specific non-ICU wards? If yes, specify the orbis internal OEBENEID here.
# filter-procedure-retrieval-additional-wards: 10170
## Batch size of the parallelized partial ACUWAVE searches
# batchsize: 200 
# prediction-model-ukb-observation-orbis-codes:
#   creatinine: 10143,131,132,17342,17360
#   lactate: 189,6037,17197
#   urea: 133,10142,17343,17361,17437

## Logging
#logging:
#  level:
#    root: debug
#    de.ukbonn.mwtek.dashboard: DEBUG
#    de.ukbonn.mwtek.dashboardlogic: DEBUG
#    de.ukbonn.mwtek.utilities: DEBUG
#  file.name: coronadashboard.log
#  file.max-size: 100MB

## In order to handle covid variants that do not yet have a loinc code at the time of completion of the current program version, it is possible to check the "display" field of the loinc coding for free text entries.
## Source of voc/voi variants: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Virologische_Basisdaten_Varianten_Nomenklatur.html
#variants:
## variants of concern that aren't supported by the dashboard yet
#  other-voc:
## variants of interest
#  non-voc: Lambda,My,Epsilon,Zeta,Eta,Theta,Iota,Kappa
